version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: languages_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: languages_pgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
  languages:
    image: snig501:languages
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
volumes:
  postgresDB:
